### ISSUE TITLE
'str' object has no attribute 'custom_id'

### ISSUE THREAD

**Issue by redmen4772** [mccoderpy/discord.py-message-components#13]
Traceback (most recent call last):
  File "c:\Users\redme\OneDrive\바탕 화면\python\bot.py", line 1444, in <module>
    client.run(token[0])
  File "C:\Users\redme\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 729, in run
    return future.result()
  File "C:\Users\redme\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 708, in runner
    await self.start(*args, **kwargs)
  File "C:\Users\redme\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 672, in start
    await self.connect(reconnect=reconnect)
  File "C:\Users\redme\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 572, in connect
    await self.ws.poll_event()
  File "C:\Users\redme\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\gateway.py", line 559, in poll_event
    await self.received_message(msg.data)
  File "C:\Users\redme\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\gateway.py", line 509, in received_message
    func(data)
  File "C:\Users\redme\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\state.py", line 561, in parse_interaction_create
    self.dispatch('button_click', interaction, interaction.component)
  File "C:\Users\redme\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\interactions.py", line 230, in component
    self._component = utils.get(self.message.all_buttons, custom_id=custom_id)
  File "C:\Users\redme\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\utils.py", line 297, in get
    if pred(elem) == v:
AttributeError: 'str' object has no attribute 'custom_id'

**Comment by mccoderpy** [comment]
What Version are you using?
